name: finn-gpt
channels:
  - defaults
  - pytorch-nightly
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch --index-url https://download.pytorch.org/whl/nightly/cu118
      - numpy
      - matplotlib
      - transformers
      - datasets
      - tiktoken
      - openai
      - flask
      - tqdm