name: finn-gpt
channels:
  - defaults
  - pytorch-nightly
dependencies:
  - python=3.8
  - pip
  - pip:
      - torch --index-url https://download.pytorch.org/whl/nightly/cu118
      - transformers
      - tiktoken
      - datasets
      - tqdm
      - flask
