FROM python:3.8-slim

WORKDIR /usr/src/app

COPY api/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY api/endpoint.py ./endpoint.py
COPY ../model.py ./
COPY ../sample.py ./
COPY ../artifacts/chat_model_02000.pt ./artifacts/chat_model_02000.pt

EXPOSE 8080

ENV isChat=1

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "endpoint:app"]